version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.0-apache
        auth:
          username: 'springfieldstar'
          password: 'SpringField!999'
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t springfieldstar/springfield . 
      - run: docker push springfieldstar/springfield